// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/game.proto

package pt

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RspLogin_RET int32

const (
	RspLogin_SUCCESS        RspLogin_RET = 0
	RspLogin_ACCOUNT_NULL   RspLogin_RET = 1
	RspLogin_ACCOUNT_LOCK   RspLogin_RET = 2
	RspLogin_PASSWORD_ERROR RspLogin_RET = 3
	RspLogin_ERROR          RspLogin_RET = 10
)

var RspLogin_RET_name = map[int32]string{
	0:  "SUCCESS",
	1:  "ACCOUNT_NULL",
	2:  "ACCOUNT_LOCK",
	3:  "PASSWORD_ERROR",
	10: "ERROR",
}

var RspLogin_RET_value = map[string]int32{
	"SUCCESS":        0,
	"ACCOUNT_NULL":   1,
	"ACCOUNT_LOCK":   2,
	"PASSWORD_ERROR": 3,
	"ERROR":          10,
}

func (x RspLogin_RET) String() string {
	return proto.EnumName(RspLogin_RET_name, int32(x))
}

func (RspLogin_RET) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_111186c904c96a69, []int{3, 0}
}

type ReqLogin struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLogin) Reset()         { *m = ReqLogin{} }
func (m *ReqLogin) String() string { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()    {}
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_111186c904c96a69, []int{0}
}

func (m *ReqLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLogin.Unmarshal(m, b)
}
func (m *ReqLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLogin.Marshal(b, m, deterministic)
}
func (m *ReqLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLogin.Merge(m, src)
}
func (m *ReqLogin) XXX_Size() int {
	return xxx_messageInfo_ReqLogin.Size(m)
}
func (m *ReqLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLogin proto.InternalMessageInfo

func (m *ReqLogin) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ReqLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ObjUserInfo struct {
	Nickname             string   `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Icon                 string   `protobuf:"bytes,2,opt,name=icon,proto3" json:"icon,omitempty"`
	Coin                 int64    `protobuf:"varint,3,opt,name=coin,proto3" json:"coin,omitempty"`
	Location             string   `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjUserInfo) Reset()         { *m = ObjUserInfo{} }
func (m *ObjUserInfo) String() string { return proto.CompactTextString(m) }
func (*ObjUserInfo) ProtoMessage()    {}
func (*ObjUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_111186c904c96a69, []int{1}
}

func (m *ObjUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjUserInfo.Unmarshal(m, b)
}
func (m *ObjUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjUserInfo.Marshal(b, m, deterministic)
}
func (m *ObjUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjUserInfo.Merge(m, src)
}
func (m *ObjUserInfo) XXX_Size() int {
	return xxx_messageInfo_ObjUserInfo.Size(m)
}
func (m *ObjUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ObjUserInfo proto.InternalMessageInfo

func (m *ObjUserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *ObjUserInfo) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *ObjUserInfo) GetCoin() int64 {
	if m != nil {
		return m.Coin
	}
	return 0
}

func (m *ObjUserInfo) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type ObjUserGameRecord struct {
	Time                 string   `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Kill                 int32    `protobuf:"varint,2,opt,name=kill,proto3" json:"kill,omitempty"`
	Dead                 int32    `protobuf:"varint,3,opt,name=dead,proto3" json:"dead,omitempty"`
	Assist               int32    `protobuf:"varint,4,opt,name=assist,proto3" json:"assist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjUserGameRecord) Reset()         { *m = ObjUserGameRecord{} }
func (m *ObjUserGameRecord) String() string { return proto.CompactTextString(m) }
func (*ObjUserGameRecord) ProtoMessage()    {}
func (*ObjUserGameRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_111186c904c96a69, []int{2}
}

func (m *ObjUserGameRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjUserGameRecord.Unmarshal(m, b)
}
func (m *ObjUserGameRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjUserGameRecord.Marshal(b, m, deterministic)
}
func (m *ObjUserGameRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjUserGameRecord.Merge(m, src)
}
func (m *ObjUserGameRecord) XXX_Size() int {
	return xxx_messageInfo_ObjUserGameRecord.Size(m)
}
func (m *ObjUserGameRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjUserGameRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ObjUserGameRecord proto.InternalMessageInfo

func (m *ObjUserGameRecord) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *ObjUserGameRecord) GetKill() int32 {
	if m != nil {
		return m.Kill
	}
	return 0
}

func (m *ObjUserGameRecord) GetDead() int32 {
	if m != nil {
		return m.Dead
	}
	return 0
}

func (m *ObjUserGameRecord) GetAssist() int32 {
	if m != nil {
		return m.Assist
	}
	return 0
}

type RspLogin struct {
	Ret                  int32                `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	UserInfo             *ObjUserInfo         `protobuf:"bytes,2,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	Record               []*ObjUserGameRecord `protobuf:"bytes,3,rep,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RspLogin) Reset()         { *m = RspLogin{} }
func (m *RspLogin) String() string { return proto.CompactTextString(m) }
func (*RspLogin) ProtoMessage()    {}
func (*RspLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_111186c904c96a69, []int{3}
}

func (m *RspLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspLogin.Unmarshal(m, b)
}
func (m *RspLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspLogin.Marshal(b, m, deterministic)
}
func (m *RspLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspLogin.Merge(m, src)
}
func (m *RspLogin) XXX_Size() int {
	return xxx_messageInfo_RspLogin.Size(m)
}
func (m *RspLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_RspLogin.DiscardUnknown(m)
}

var xxx_messageInfo_RspLogin proto.InternalMessageInfo

func (m *RspLogin) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *RspLogin) GetUserInfo() *ObjUserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *RspLogin) GetRecord() []*ObjUserGameRecord {
	if m != nil {
		return m.Record
	}
	return nil
}

func init() {
	proto.RegisterEnum("pt.RspLogin_RET", RspLogin_RET_name, RspLogin_RET_value)
	proto.RegisterType((*ReqLogin)(nil), "pt.req_login")
	proto.RegisterType((*ObjUserInfo)(nil), "pt.obj_user_info")
	proto.RegisterType((*ObjUserGameRecord)(nil), "pt.obj_user_game_record")
	proto.RegisterType((*RspLogin)(nil), "pt.rsp_login")
}

func init() { proto.RegisterFile("protobuf/game.proto", fileDescriptor_111186c904c96a69) }

var fileDescriptor_111186c904c96a69 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x52, 0xc1, 0x6e, 0xa3, 0x30,
	0x14, 0x5c, 0x70, 0xc8, 0x2e, 0x2f, 0xbb, 0x2b, 0xea, 0x56, 0x15, 0xea, 0x29, 0xe2, 0x94, 0x13,
	0xad, 0xd2, 0x2f, 0x48, 0x69, 0xa4, 0x56, 0x8d, 0x42, 0x65, 0x82, 0x7a, 0x44, 0x04, 0x48, 0xe4,
	0x84, 0xd8, 0xd4, 0x76, 0xd4, 0x3f, 0xed, 0xf7, 0x54, 0x36, 0x04, 0x25, 0xb7, 0x99, 0xf1, 0x68,
	0x86, 0x37, 0x02, 0xae, 0x1b, 0xc1, 0x15, 0x5f, 0x1f, 0x37, 0xf7, 0xdb, 0xfc, 0x50, 0x85, 0x86,
	0x61, 0xbb, 0x51, 0x41, 0x04, 0xae, 0xa8, 0x3e, 0xb3, 0x9a, 0x6f, 0x29, 0xc3, 0x77, 0xf0, 0xe7,
	0x28, 0x2b, 0xc1, 0xf2, 0x43, 0xe5, 0x5b, 0x63, 0x6b, 0xe2, 0x92, 0x9e, 0xeb, 0xb7, 0x26, 0x97,
	0xf2, 0x8b, 0x8b, 0xd2, 0xb7, 0xdb, 0xb7, 0x13, 0x0f, 0x38, 0xfc, 0xe3, 0xeb, 0x5d, 0xa6, 0xbd,
	0x19, 0x65, 0x1b, 0xae, 0xcd, 0x8c, 0x16, 0xfb, 0xf3, 0xa0, 0x13, 0xc7, 0x18, 0x06, 0xb4, 0xe0,
	0xac, 0x0b, 0x31, 0x58, 0x6b, 0x05, 0xa7, 0xcc, 0x47, 0x63, 0x6b, 0x82, 0x88, 0xc1, 0x3a, 0xa3,
	0xe6, 0x45, 0xae, 0x28, 0x67, 0xfe, 0xa0, 0xcd, 0x38, 0xf1, 0x60, 0x07, 0x37, 0x7d, 0xa1, 0x3e,
	0x28, 0x13, 0x55, 0xc1, 0x45, 0xa9, 0x73, 0x14, 0xed, 0x3b, 0x0d, 0xd6, 0xda, 0x9e, 0xd6, 0xb5,
	0xe9, 0x73, 0x88, 0xc1, 0x5a, 0x2b, 0xab, 0xbc, 0x34, 0x7d, 0x0e, 0x31, 0x18, 0xdf, 0xc2, 0x30,
	0x97, 0x92, 0x4a, 0x65, 0xda, 0x1c, 0xd2, 0xb1, 0xe0, 0xdb, 0x02, 0x57, 0xc8, 0xa6, 0x9b, 0xc8,
	0x03, 0x24, 0x2a, 0x65, 0x0a, 0x1c, 0xa2, 0x21, 0x0e, 0xc1, 0xed, 0x0f, 0x37, 0x25, 0xa3, 0xe9,
	0x55, 0xd8, 0xa8, 0xf0, 0x62, 0x91, 0x76, 0xc8, 0x57, 0xbd, 0xcd, 0x03, 0x0c, 0xdb, 0xaf, 0xf5,
	0xd1, 0x18, 0x4d, 0x46, 0x53, 0xff, 0xc2, 0x7c, 0x76, 0x0d, 0xe9, 0x7c, 0x41, 0x0a, 0x88, 0xcc,
	0x57, 0x78, 0x04, 0xbf, 0x93, 0x34, 0x8a, 0xe6, 0x49, 0xe2, 0xfd, 0xc2, 0x1e, 0xfc, 0x9d, 0x45,
	0x51, 0x9c, 0x2e, 0x57, 0xd9, 0x32, 0x5d, 0x2c, 0x3c, 0xeb, 0x5c, 0x59, 0xc4, 0xd1, 0x9b, 0x67,
	0x63, 0x0c, 0xff, 0xdf, 0x67, 0x49, 0xf2, 0x11, 0x93, 0xe7, 0x6c, 0x4e, 0x48, 0x4c, 0x3c, 0x84,
	0x5d, 0x70, 0x5a, 0x08, 0x4f, 0xf6, 0x0b, 0x5a, 0x0f, 0xcd, 0x9f, 0xf0, 0xf8, 0x13, 0x00, 0x00,
	0xff, 0xff, 0xe2, 0x30, 0x44, 0xaa, 0x20, 0x02, 0x00, 0x00,
}
