// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

#ifndef PROTOBUF_game_2eproto__INCLUDED
#define PROTOBUF_game_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)

namespace pt {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_game_2eproto();
void protobuf_AssignDesc_game_2eproto();
void protobuf_ShutdownFile_game_2eproto();

class obj_user_game_record;
class obj_user_info;
class req_login;
class rsp_login;

enum rsp_login_RET {
  rsp_login_RET_SUCCESS = 0,
  rsp_login_RET_ACCOUNT_NULL = 1,
  rsp_login_RET_ACCOUNT_LOCK = 2,
  rsp_login_RET_PASSWORD_ERROR = 3,
  rsp_login_RET_ERROR = 10,
  rsp_login_RET_rsp_login_RET_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  rsp_login_RET_rsp_login_RET_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool rsp_login_RET_IsValid(int value);
const rsp_login_RET rsp_login_RET_RET_MIN = rsp_login_RET_SUCCESS;
const rsp_login_RET rsp_login_RET_RET_MAX = rsp_login_RET_ERROR;
const int rsp_login_RET_RET_ARRAYSIZE = rsp_login_RET_RET_MAX + 1;

// ===================================================================

class req_login : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:pt.req_login) */ {
 public:
  req_login();
  virtual ~req_login();

  req_login(const req_login& from);

  inline req_login& operator=(const req_login& from) {
    CopyFrom(from);
    return *this;
  }

  static const req_login& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const req_login* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(req_login* other);

  // implements Message ----------------------------------------------

  inline req_login* New() const { return New(NULL); }

  req_login* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const req_login& from);
  void MergeFrom(const req_login& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(req_login* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string username = 1;
  void clear_username();
  static const int kUsernameFieldNumber = 1;
  const ::std::string& username() const;
  void set_username(const ::std::string& value);
  void set_username(const char* value);
  void set_username(const char* value, size_t size);
  ::std::string* mutable_username();
  ::std::string* release_username();
  void set_allocated_username(::std::string* username);

  // optional string password = 2;
  void clear_password();
  static const int kPasswordFieldNumber = 2;
  const ::std::string& password() const;
  void set_password(const ::std::string& value);
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  ::std::string* mutable_password();
  ::std::string* release_password();
  void set_allocated_password(::std::string* password);

  // @@protoc_insertion_point(class_scope:pt.req_login)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr username_;
  ::google::protobuf::internal::ArenaStringPtr password_;
  mutable int _cached_size_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_game_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_game_2eproto();
  #endif
  friend void protobuf_AssignDesc_game_2eproto();
  friend void protobuf_ShutdownFile_game_2eproto();

  void InitAsDefaultInstance();
  static req_login* default_instance_;
};
// -------------------------------------------------------------------

class obj_user_info : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:pt.obj_user_info) */ {
 public:
  obj_user_info();
  virtual ~obj_user_info();

  obj_user_info(const obj_user_info& from);

  inline obj_user_info& operator=(const obj_user_info& from) {
    CopyFrom(from);
    return *this;
  }

  static const obj_user_info& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const obj_user_info* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(obj_user_info* other);

  // implements Message ----------------------------------------------

  inline obj_user_info* New() const { return New(NULL); }

  obj_user_info* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const obj_user_info& from);
  void MergeFrom(const obj_user_info& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(obj_user_info* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string nickname = 1;
  void clear_nickname();
  static const int kNicknameFieldNumber = 1;
  const ::std::string& nickname() const;
  void set_nickname(const ::std::string& value);
  void set_nickname(const char* value);
  void set_nickname(const char* value, size_t size);
  ::std::string* mutable_nickname();
  ::std::string* release_nickname();
  void set_allocated_nickname(::std::string* nickname);

  // optional string icon = 2;
  void clear_icon();
  static const int kIconFieldNumber = 2;
  const ::std::string& icon() const;
  void set_icon(const ::std::string& value);
  void set_icon(const char* value);
  void set_icon(const char* value, size_t size);
  ::std::string* mutable_icon();
  ::std::string* release_icon();
  void set_allocated_icon(::std::string* icon);

  // optional int64 coin = 3;
  void clear_coin();
  static const int kCoinFieldNumber = 3;
  ::google::protobuf::int64 coin() const;
  void set_coin(::google::protobuf::int64 value);

  // optional string location = 4;
  void clear_location();
  static const int kLocationFieldNumber = 4;
  const ::std::string& location() const;
  void set_location(const ::std::string& value);
  void set_location(const char* value);
  void set_location(const char* value, size_t size);
  ::std::string* mutable_location();
  ::std::string* release_location();
  void set_allocated_location(::std::string* location);

  // @@protoc_insertion_point(class_scope:pt.obj_user_info)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr nickname_;
  ::google::protobuf::internal::ArenaStringPtr icon_;
  ::google::protobuf::int64 coin_;
  ::google::protobuf::internal::ArenaStringPtr location_;
  mutable int _cached_size_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_game_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_game_2eproto();
  #endif
  friend void protobuf_AssignDesc_game_2eproto();
  friend void protobuf_ShutdownFile_game_2eproto();

  void InitAsDefaultInstance();
  static obj_user_info* default_instance_;
};
// -------------------------------------------------------------------

class obj_user_game_record : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:pt.obj_user_game_record) */ {
 public:
  obj_user_game_record();
  virtual ~obj_user_game_record();

  obj_user_game_record(const obj_user_game_record& from);

  inline obj_user_game_record& operator=(const obj_user_game_record& from) {
    CopyFrom(from);
    return *this;
  }

  static const obj_user_game_record& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const obj_user_game_record* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(obj_user_game_record* other);

  // implements Message ----------------------------------------------

  inline obj_user_game_record* New() const { return New(NULL); }

  obj_user_game_record* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const obj_user_game_record& from);
  void MergeFrom(const obj_user_game_record& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(obj_user_game_record* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string time = 1;
  void clear_time();
  static const int kTimeFieldNumber = 1;
  const ::std::string& time() const;
  void set_time(const ::std::string& value);
  void set_time(const char* value);
  void set_time(const char* value, size_t size);
  ::std::string* mutable_time();
  ::std::string* release_time();
  void set_allocated_time(::std::string* time);

  // optional int32 kill = 2;
  void clear_kill();
  static const int kKillFieldNumber = 2;
  ::google::protobuf::int32 kill() const;
  void set_kill(::google::protobuf::int32 value);

  // optional int32 dead = 3;
  void clear_dead();
  static const int kDeadFieldNumber = 3;
  ::google::protobuf::int32 dead() const;
  void set_dead(::google::protobuf::int32 value);

  // optional int32 assist = 4;
  void clear_assist();
  static const int kAssistFieldNumber = 4;
  ::google::protobuf::int32 assist() const;
  void set_assist(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:pt.obj_user_game_record)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr time_;
  ::google::protobuf::int32 kill_;
  ::google::protobuf::int32 dead_;
  ::google::protobuf::int32 assist_;
  mutable int _cached_size_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_game_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_game_2eproto();
  #endif
  friend void protobuf_AssignDesc_game_2eproto();
  friend void protobuf_ShutdownFile_game_2eproto();

  void InitAsDefaultInstance();
  static obj_user_game_record* default_instance_;
};
// -------------------------------------------------------------------

class rsp_login : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:pt.rsp_login) */ {
 public:
  rsp_login();
  virtual ~rsp_login();

  rsp_login(const rsp_login& from);

  inline rsp_login& operator=(const rsp_login& from) {
    CopyFrom(from);
    return *this;
  }

  static const rsp_login& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const rsp_login* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(rsp_login* other);

  // implements Message ----------------------------------------------

  inline rsp_login* New() const { return New(NULL); }

  rsp_login* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const rsp_login& from);
  void MergeFrom(const rsp_login& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(rsp_login* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  typedef rsp_login_RET RET;
  static const RET SUCCESS =
    rsp_login_RET_SUCCESS;
  static const RET ACCOUNT_NULL =
    rsp_login_RET_ACCOUNT_NULL;
  static const RET ACCOUNT_LOCK =
    rsp_login_RET_ACCOUNT_LOCK;
  static const RET PASSWORD_ERROR =
    rsp_login_RET_PASSWORD_ERROR;
  static const RET ERROR =
    rsp_login_RET_ERROR;
  static inline bool RET_IsValid(int value) {
    return rsp_login_RET_IsValid(value);
  }
  static const RET RET_MIN =
    rsp_login_RET_RET_MIN;
  static const RET RET_MAX =
    rsp_login_RET_RET_MAX;
  static const int RET_ARRAYSIZE =
    rsp_login_RET_RET_ARRAYSIZE;

  // accessors -------------------------------------------------------

  // optional int32 ret = 1;
  void clear_ret();
  static const int kRetFieldNumber = 1;
  ::google::protobuf::int32 ret() const;
  void set_ret(::google::protobuf::int32 value);

  // optional .pt.obj_user_info user_info = 2;
  bool has_user_info() const;
  void clear_user_info();
  static const int kUserInfoFieldNumber = 2;
  const ::pt::obj_user_info& user_info() const;
  ::pt::obj_user_info* mutable_user_info();
  ::pt::obj_user_info* release_user_info();
  void set_allocated_user_info(::pt::obj_user_info* user_info);

  // repeated .pt.obj_user_game_record record = 3;
  int record_size() const;
  void clear_record();
  static const int kRecordFieldNumber = 3;
  const ::pt::obj_user_game_record& record(int index) const;
  ::pt::obj_user_game_record* mutable_record(int index);
  ::pt::obj_user_game_record* add_record();
  ::google::protobuf::RepeatedPtrField< ::pt::obj_user_game_record >*
      mutable_record();
  const ::google::protobuf::RepeatedPtrField< ::pt::obj_user_game_record >&
      record() const;

  // @@protoc_insertion_point(class_scope:pt.rsp_login)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  bool _is_default_instance_;
  ::pt::obj_user_info* user_info_;
  ::google::protobuf::RepeatedPtrField< ::pt::obj_user_game_record > record_;
  ::google::protobuf::int32 ret_;
  mutable int _cached_size_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_game_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_game_2eproto();
  #endif
  friend void protobuf_AssignDesc_game_2eproto();
  friend void protobuf_ShutdownFile_game_2eproto();

  void InitAsDefaultInstance();
  static rsp_login* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// req_login

// optional string username = 1;
inline void req_login::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& req_login::username() const {
  // @@protoc_insertion_point(field_get:pt.req_login.username)
  return username_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void req_login::set_username(const ::std::string& value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pt.req_login.username)
}
inline void req_login::set_username(const char* value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pt.req_login.username)
}
inline void req_login::set_username(const char* value, size_t size) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pt.req_login.username)
}
inline ::std::string* req_login::mutable_username() {
  
  // @@protoc_insertion_point(field_mutable:pt.req_login.username)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* req_login::release_username() {
  // @@protoc_insertion_point(field_release:pt.req_login.username)
  
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void req_login::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    
  } else {
    
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:pt.req_login.username)
}

// optional string password = 2;
inline void req_login::clear_password() {
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& req_login::password() const {
  // @@protoc_insertion_point(field_get:pt.req_login.password)
  return password_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void req_login::set_password(const ::std::string& value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pt.req_login.password)
}
inline void req_login::set_password(const char* value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pt.req_login.password)
}
inline void req_login::set_password(const char* value, size_t size) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pt.req_login.password)
}
inline ::std::string* req_login::mutable_password() {
  
  // @@protoc_insertion_point(field_mutable:pt.req_login.password)
  return password_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* req_login::release_password() {
  // @@protoc_insertion_point(field_release:pt.req_login.password)
  
  return password_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void req_login::set_allocated_password(::std::string* password) {
  if (password != NULL) {
    
  } else {
    
  }
  password_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:pt.req_login.password)
}

// -------------------------------------------------------------------

// obj_user_info

// optional string nickname = 1;
inline void obj_user_info::clear_nickname() {
  nickname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& obj_user_info::nickname() const {
  // @@protoc_insertion_point(field_get:pt.obj_user_info.nickname)
  return nickname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void obj_user_info::set_nickname(const ::std::string& value) {
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pt.obj_user_info.nickname)
}
inline void obj_user_info::set_nickname(const char* value) {
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pt.obj_user_info.nickname)
}
inline void obj_user_info::set_nickname(const char* value, size_t size) {
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pt.obj_user_info.nickname)
}
inline ::std::string* obj_user_info::mutable_nickname() {
  
  // @@protoc_insertion_point(field_mutable:pt.obj_user_info.nickname)
  return nickname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* obj_user_info::release_nickname() {
  // @@protoc_insertion_point(field_release:pt.obj_user_info.nickname)
  
  return nickname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void obj_user_info::set_allocated_nickname(::std::string* nickname) {
  if (nickname != NULL) {
    
  } else {
    
  }
  nickname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), nickname);
  // @@protoc_insertion_point(field_set_allocated:pt.obj_user_info.nickname)
}

// optional string icon = 2;
inline void obj_user_info::clear_icon() {
  icon_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& obj_user_info::icon() const {
  // @@protoc_insertion_point(field_get:pt.obj_user_info.icon)
  return icon_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void obj_user_info::set_icon(const ::std::string& value) {
  
  icon_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pt.obj_user_info.icon)
}
inline void obj_user_info::set_icon(const char* value) {
  
  icon_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pt.obj_user_info.icon)
}
inline void obj_user_info::set_icon(const char* value, size_t size) {
  
  icon_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pt.obj_user_info.icon)
}
inline ::std::string* obj_user_info::mutable_icon() {
  
  // @@protoc_insertion_point(field_mutable:pt.obj_user_info.icon)
  return icon_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* obj_user_info::release_icon() {
  // @@protoc_insertion_point(field_release:pt.obj_user_info.icon)
  
  return icon_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void obj_user_info::set_allocated_icon(::std::string* icon) {
  if (icon != NULL) {
    
  } else {
    
  }
  icon_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), icon);
  // @@protoc_insertion_point(field_set_allocated:pt.obj_user_info.icon)
}

// optional int64 coin = 3;
inline void obj_user_info::clear_coin() {
  coin_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 obj_user_info::coin() const {
  // @@protoc_insertion_point(field_get:pt.obj_user_info.coin)
  return coin_;
}
inline void obj_user_info::set_coin(::google::protobuf::int64 value) {
  
  coin_ = value;
  // @@protoc_insertion_point(field_set:pt.obj_user_info.coin)
}

// optional string location = 4;
inline void obj_user_info::clear_location() {
  location_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& obj_user_info::location() const {
  // @@protoc_insertion_point(field_get:pt.obj_user_info.location)
  return location_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void obj_user_info::set_location(const ::std::string& value) {
  
  location_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pt.obj_user_info.location)
}
inline void obj_user_info::set_location(const char* value) {
  
  location_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pt.obj_user_info.location)
}
inline void obj_user_info::set_location(const char* value, size_t size) {
  
  location_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pt.obj_user_info.location)
}
inline ::std::string* obj_user_info::mutable_location() {
  
  // @@protoc_insertion_point(field_mutable:pt.obj_user_info.location)
  return location_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* obj_user_info::release_location() {
  // @@protoc_insertion_point(field_release:pt.obj_user_info.location)
  
  return location_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void obj_user_info::set_allocated_location(::std::string* location) {
  if (location != NULL) {
    
  } else {
    
  }
  location_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), location);
  // @@protoc_insertion_point(field_set_allocated:pt.obj_user_info.location)
}

// -------------------------------------------------------------------

// obj_user_game_record

// optional string time = 1;
inline void obj_user_game_record::clear_time() {
  time_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& obj_user_game_record::time() const {
  // @@protoc_insertion_point(field_get:pt.obj_user_game_record.time)
  return time_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void obj_user_game_record::set_time(const ::std::string& value) {
  
  time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pt.obj_user_game_record.time)
}
inline void obj_user_game_record::set_time(const char* value) {
  
  time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pt.obj_user_game_record.time)
}
inline void obj_user_game_record::set_time(const char* value, size_t size) {
  
  time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pt.obj_user_game_record.time)
}
inline ::std::string* obj_user_game_record::mutable_time() {
  
  // @@protoc_insertion_point(field_mutable:pt.obj_user_game_record.time)
  return time_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* obj_user_game_record::release_time() {
  // @@protoc_insertion_point(field_release:pt.obj_user_game_record.time)
  
  return time_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void obj_user_game_record::set_allocated_time(::std::string* time) {
  if (time != NULL) {
    
  } else {
    
  }
  time_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), time);
  // @@protoc_insertion_point(field_set_allocated:pt.obj_user_game_record.time)
}

// optional int32 kill = 2;
inline void obj_user_game_record::clear_kill() {
  kill_ = 0;
}
inline ::google::protobuf::int32 obj_user_game_record::kill() const {
  // @@protoc_insertion_point(field_get:pt.obj_user_game_record.kill)
  return kill_;
}
inline void obj_user_game_record::set_kill(::google::protobuf::int32 value) {
  
  kill_ = value;
  // @@protoc_insertion_point(field_set:pt.obj_user_game_record.kill)
}

// optional int32 dead = 3;
inline void obj_user_game_record::clear_dead() {
  dead_ = 0;
}
inline ::google::protobuf::int32 obj_user_game_record::dead() const {
  // @@protoc_insertion_point(field_get:pt.obj_user_game_record.dead)
  return dead_;
}
inline void obj_user_game_record::set_dead(::google::protobuf::int32 value) {
  
  dead_ = value;
  // @@protoc_insertion_point(field_set:pt.obj_user_game_record.dead)
}

// optional int32 assist = 4;
inline void obj_user_game_record::clear_assist() {
  assist_ = 0;
}
inline ::google::protobuf::int32 obj_user_game_record::assist() const {
  // @@protoc_insertion_point(field_get:pt.obj_user_game_record.assist)
  return assist_;
}
inline void obj_user_game_record::set_assist(::google::protobuf::int32 value) {
  
  assist_ = value;
  // @@protoc_insertion_point(field_set:pt.obj_user_game_record.assist)
}

// -------------------------------------------------------------------

// rsp_login

// optional int32 ret = 1;
inline void rsp_login::clear_ret() {
  ret_ = 0;
}
inline ::google::protobuf::int32 rsp_login::ret() const {
  // @@protoc_insertion_point(field_get:pt.rsp_login.ret)
  return ret_;
}
inline void rsp_login::set_ret(::google::protobuf::int32 value) {
  
  ret_ = value;
  // @@protoc_insertion_point(field_set:pt.rsp_login.ret)
}

// optional .pt.obj_user_info user_info = 2;
inline bool rsp_login::has_user_info() const {
  return !_is_default_instance_ && user_info_ != NULL;
}
inline void rsp_login::clear_user_info() {
  if (GetArenaNoVirtual() == NULL && user_info_ != NULL) delete user_info_;
  user_info_ = NULL;
}
inline const ::pt::obj_user_info& rsp_login::user_info() const {
  // @@protoc_insertion_point(field_get:pt.rsp_login.user_info)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return user_info_ != NULL ? *user_info_ : *default_instance().user_info_;
#else
  return user_info_ != NULL ? *user_info_ : *default_instance_->user_info_;
#endif
}
inline ::pt::obj_user_info* rsp_login::mutable_user_info() {
  
  if (user_info_ == NULL) {
    user_info_ = new ::pt::obj_user_info;
  }
  // @@protoc_insertion_point(field_mutable:pt.rsp_login.user_info)
  return user_info_;
}
inline ::pt::obj_user_info* rsp_login::release_user_info() {
  // @@protoc_insertion_point(field_release:pt.rsp_login.user_info)
  
  ::pt::obj_user_info* temp = user_info_;
  user_info_ = NULL;
  return temp;
}
inline void rsp_login::set_allocated_user_info(::pt::obj_user_info* user_info) {
  delete user_info_;
  user_info_ = user_info;
  if (user_info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:pt.rsp_login.user_info)
}

// repeated .pt.obj_user_game_record record = 3;
inline int rsp_login::record_size() const {
  return record_.size();
}
inline void rsp_login::clear_record() {
  record_.Clear();
}
inline const ::pt::obj_user_game_record& rsp_login::record(int index) const {
  // @@protoc_insertion_point(field_get:pt.rsp_login.record)
  return record_.Get(index);
}
inline ::pt::obj_user_game_record* rsp_login::mutable_record(int index) {
  // @@protoc_insertion_point(field_mutable:pt.rsp_login.record)
  return record_.Mutable(index);
}
inline ::pt::obj_user_game_record* rsp_login::add_record() {
  // @@protoc_insertion_point(field_add:pt.rsp_login.record)
  return record_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::pt::obj_user_game_record >*
rsp_login::mutable_record() {
  // @@protoc_insertion_point(field_mutable_list:pt.rsp_login.record)
  return &record_;
}
inline const ::google::protobuf::RepeatedPtrField< ::pt::obj_user_game_record >&
rsp_login::record() const {
  // @@protoc_insertion_point(field_list:pt.rsp_login.record)
  return record_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pt

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::pt::rsp_login_RET> : ::google::protobuf::internal::true_type {};

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_game_2eproto__INCLUDED
